app_auth/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('login', login_gym, name='login-gym'),
    path('register', register, name='register'),
    path('logout', logout_gym, name='logout'),
]

club_gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from gym.views import home, detail, search, sms

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index.html', home, name="home"),
    path('abonnement/<int:id_abonnement>', detail, name="detail"),
    path('abonnement/recherche', search, name="search"),
    path('message-sms', sms, name="sms"),
    path('auth/', include("app_auth.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gym/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index.html', views.home, name='home'),
]

app_auth/models.py
from django.db import models

# Create your models here.

gym/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=120)

    def __str__(self):
        return self.name

class Abonnement(models.Model):
    title=models.CharField(max_length=50)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    desc=models.TextField()
    image=models.ImageField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

app_auth/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur", widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'class':'form-control'}))

class RegisterForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur", widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'class':'form-control'}))
    pwd_confirmation = forms.CharField(label="Confirmer le mot de passe", widget=forms.PasswordInput(attrs={'class':'form-control'}))

app_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate,login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *

def login_gym(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = authenticate(username=username, password=pwd)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.error(request, "Authentification échouée")
                return render(request,"login.html", {'form':form})
        else:
            for field in form.errors:
                form[field].field.widget.attrs['class'] += ' is-invalid'

            return render(request,"login.html", {'form':form})
    else:
            form = LoginForm()
    return render(request,"login.html", {'form':form})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = User.objects.create_user(username=username, password=pwd)
            if user is not None:
                return redirect("login-gym")
            else:
                messages.error(request, 'Création de compte échouée')
                return render(request, 'register.html', {'form':form})

        else:
            return render(request, 'register.html', {'form':form})
            return render(request, 'register.html', {})
    else:
         form = RegisterForm()
    return render(request, 'register.html', {'form':form})

def logout_gym(request):
    logout(request)
    return redirect("login-gym")

gym/views.py
from django.shortcuts import render
from .models import Abonnement

def home(request):
    list_abonnements=Abonnement.objects.all()
    context={"liste_abonnements":list_abonnements}
    return render(request, "index.html", context)

def detail(request, id_abonnement):
    abonnement=Abonnement.objects.get(id=id_abonnement)
    category=abonnement.category
    abonnements_en_relation=Abonnement.objects.filter(category=category)[:5]
    return render(request, 'detail.html', {"abonnement":abonnement, "aer":abonnements_en_relation})

def search(request):
    query=request.GET["abonnement"]
    liste_abonnement= Abonnement.objects.filter(title__icontains=query)
    return render(request, "search.html", {"liste_abonnement":liste_abonnement})


def sms(request):
    message=request.GET['body']
    message_splited=message.split("-")
    title=message_splited[0]
    desc=message_splited[1]

    etud_category=Category.objects.get(id=2)
    abonnement= Abonnement(title=title, category=etud_category, desc=desc, image="http://default")
    abonnement.save()
    print('data saved successfully')
    return HttpResponse("data saved successfully")

app_auth/templates/login.html
{% extends 'base.html' %}

{% block title %} Connexion au gym {% endblock %}

{% block content %}

<div class="container">
    <div class="col-md-12 mt-5">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger text-center"><strong>{{message}}</strong></div>
        {% endfor %}
        {% endif %}

        <form action="" method="POST" novalidate> {% csrf_token %}
            <div class="card">
                <div class="card-header text-center"><i class="fas fa-user"></i> Connexion au gym</div>
                <div class="card-body">
                     <label for="id_username">Nom utilisateur :</label>
                     {% if form.username.errors %}
                     {% for error in form.username.errors %}
                <div class="div-error-{{form.username.name}}"><small class="text-danger">{{error}}</small></div>
                     {% endfor %}
                     {% endif %}
                     {{form.username}}

                     <label for="id_pwd">Mot de passe :</label> 
                     {% if form.pwd.errors %}
                     {% for error in form.pwd.errors %}
                <div class="div-error-{{form.pwd.name}}"><small class="text-danger">{{error}}</small></div>
                     {% endfor %}
                     {% endif %}
                     {{form.pwd}}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary btn-block">Se connecter</button>
                    <p class="mt-2">Vous n'avez pas de compte ?<a href="{% url 'register' %}"> Créer un compte</a></p>
                </div>
        
            </div>

        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function(){
        $('input').keyup(function(){
            let textSaisi = $(this).val();

            let attrName= $(this).attr('name');
            let validatorElement = ".div-error-"+attrName;
            if(textSaisi === ""){
                if(!$(this).hasClass('is-invalid')){
                    $(this).addClass('is-invalid');
                    $(validatorElement).show();
            }
            } else {
                $(this).removeClass('is-invalid');

                $(validatorElement).hide();
            }
            
        })

    })
</script>
{% endblock %}

app_auth/templates/register.html
{% extends 'base.html' %}

{% block title %} Création de compte {% endblock %}

{% block content %}

<div class="container">
    <div class="col-md-12 mt-5">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger text-center"><strong>{{message}}</strong></div>
        {% endfor %}
        {% endif %}

        <form action="" method="POST" novalidate> {% csrf_token %}
            <div class="card">
                <div class="card-header text-center"><i class="fas fa-user-lock"></i> Création de compte</div>
                <div class="card-body">
                    {{form}}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary btn-block">Créer le compte</button>
                </div>
            </div>

        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}

{% endblock %}

gym/templates/_footer.html
<!-- Footer -->
<footer class="page-footer font-small mdb-color darken-3 pt-4">

    <!-- Footer Elements -->
    <div class="container">
  
      <!--Grid row-->
      <div class="row d-flex justify-content-center">
  
        <!--Grid column-->
        <div class="col-md-6">
  
          <!-- Video -->
          <div class="embed-responsive embed-responsive-16by9 mb-4">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/vlDzYIIOYmM"
              allowfullscreen></iframe>
          </div>
  
        </div>
        <!--Grid column-->
  
      </div>
      <!--Grid row-->
  
    </div>
    <!-- Footer Elements -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="/"> MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->

gym/templates/_nav.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="#">Club Gym</a>
  
    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">
  
      <!-- Links -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Admin
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
  
        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Mon compte</a>
          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
  
      </ul>
      <!-- Links -->
      {% if user.is_authenticated %}
      <a href="{% url 'logout' %}" class="btn btn-info">Deconnexion</a>
      {% else %}
      <a href="{% url 'login-gym' %}" class="btn btn-info">Connexion</a>
      {% endif %}
      <form class="form-inline" action="{% url 'search' %}">
        <div class="md-form my-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Recherche" aria-label="Search" name="abonnement">
        </div>
      </form>
    </div>
    <!-- Collapsible content -->
  
  </nav>
  <!--/.Navbar-->

gym/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Club Gym {% endblock %}</title>
     <!-- MDB icon -->
  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include "_nav.html" %}

    {% block content %}
    {% endblock %}

    {% include "_footer.html" %}
    <!-- jQuery -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript"></script>
    
</body>
</html>

gym/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2 class="text-center mt-2">Detail abonnement</h2>
            <img src="{{abonnement.image.url}}" alt="" style="max-width:600px;">
            <h3>{{abonnement.title}}</h3>
            <p>{{abonnement.desc}}</p>
        </div>
        <div class="col-md-4">
            <h5 class="mt-2">Les différents types d'abonnements</h5 class="mt-2">
                <div class="row">

                    {% for abn in aer %}
                    {% if abn.id != abonnement.id %}
                    <div class="col-md-7 mb-1">
                        {% if abn.image != "http://default" %}
                        <img src="{{abn.image.url}}" alt="" style="max-width: 180px;">
                        {% else %}
                        <img class="card-img-top" src="https://via.placeholder.com/400x300" alt="Card image cap" style="max-width: 180px;">
                        {% endif %}
                    </div>
                    <div class="col-5">
                      <strong>{{abn.title}}</strong> <br>
                      {{abn.desc | truncatewords:7}}
                    </div>
                    {% endif %}
                    {% endfor%}
                </div>
        </div>
    </div>
</div>
{% endblock %}

gym/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <h1 class="text-center mt-3">Bienvenue sur mon blog</h1>
  <div class="container">
      <div class="row">
           {% for abonnement in liste_abonnements %}
            <div class="col-12 col-md-6 col-lg-3 col-xl-3">
               <div class="card mb-3 p-2">

                    <!-- Card image -->
                    {% if abonnement.image == "http://default" %}
                    <a href="{% url 'detail' abonnement.id %}">
                        <img class="card-img-top" src="{%  static 'img/igym.jpg' %}" alt="Card image cap" style="height: 200px;">
                    </a>

                    {% else %}
                    <a href="{% url 'detail' abonnement.id %}">
                        <img class="card-img-top" src="{{abonnement.image.url}}" alt="Card image cap" style="height: 200px;">
                    </a>
                    {% endif %}
                    
  
                    <!-- Card content -->
                    <div class="card-body" style="height: 240px;">
  
                       <!-- Title -->
                       <h4 class="card-title"><a href="{% url 'detail' abonnement.id %}">{{abonnement.title}}</a></h4>
                       <!-- Text -->
                       <p class="card-text">{{abonnement.desc|truncatewords:8}}</p>
                       <p class="card-text">Publié il y a {{abonnement.created_at|timesince}}</p>
                       <!-- Button -->
                       <a href="{% url 'detail' abonnement.id %}" class="btn btn-primary">Lire la suite</a>
  
                    </div>
  
                </div>
                <!-- endCard -->
            </div>
            {% endfor %}
        </div>
        <!-- endrow -->
  </div>

{% endblock%}

gym/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Abonnement rechercher</h2>
    <div class="row">
      {% for abonnement in liste_abonnement %}
     
      <div class="col-12 col-md-6 col-lg-3 col-xl-3">
        <div class="card mb-3 p-2">

             <!-- Card image -->
             {% if abonnement.image == "http://default" %}
             <a href="{% url 'detail' abonnement.id %}">
                 <img class="card-img-top" src="{%  static 'img/igym.jpg' %}" alt="Card image cap" style="height: 200px;">
             </a>

             {% else %}
             <a href="{% url 'detail' abonnement.id %}">
                 <img class="card-img-top" src="{{abonnement.image.url}}" alt="Card image cap" style="height: 200px;">
             </a>
             {% endif %}
             

             <!-- Card content -->
             <div class="card-body" style="height: 240px;">

                <!-- Title -->
                <h4 class="card-title"><a href="{% url 'detail' abonnement.id %}">{{abonnement.title}}</a></h4>
                <!-- Text -->
                <p class="card-text">{{abonnement.desc|truncatewords:8}}</p>
                <p class="card-text">Publié il y a {{abonnement.created_at|timesince}}</p>
                <!-- Button -->
                <a href="{% url 'detail' abonnement.id %}" class="btn btn-primary">Lire la suite</a>

             </div>

         </div>
         <!-- endCard -->
     </div>
      {% endfor %}

    </div>
     
</div>
{% endblock %}